# Generated by Django 4.0.4 on 2022-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_contents_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents_review',
            field=models.TextField(default='댓글없음'),
        ),
    ]
