# Generated by Django 4.0.4 on 2022-05-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_contents_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contents_review',
        ),
    ]
