# Generated by Django 4.0.4 on 2022-05-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_contents_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contents_review',
            field=models.TextField(default=0),
        ),
    ]
